New model class that handles SKLearn models
mars-vision/marsvision pull request #13
Opened 2020-11-26 22:25 UTC by dpalencia

2021-02-03 23:41 UTC, michaelmunje commented
After this is merged, we need to make sure documentation works properly. If not, we will have to patch it by reviewing the .gitignore changes.

2021-02-10 18:49 UTC, michaelmunje requested changes
Added a few requests but other than that everything looks good and should be ready to merge soon.

2021-02-10 18:49 UTC, michaelmunje commented on marsvision/pipeline/Model.py
> +    def predict(self, image: np.ndarray):
This function should have an input of an array of images.

2021-02-10 18:49 UTC, michaelmunje commented on marsvision/pipeline/SlidingWindow.py
> +        for y in range(0, image.shape[0], self.stride_x):
Rather than a loop we are going to want to send a batch of images to this inference function.

2021-02-10 18:49 UTC, michaelmunje commented on marsvision/pipeline/SlidingWindow.py
> +            for x in range(0, image.shape[1], self.stride_y):
If the image height cannot fit N stride_y's exactly, then some portion of the image will never be reached. Therefore, there is an edge case for the very end regions of the image (rightmost or bottommost).

2021-02-14 22:45 UTC, dpalencia commented on marsvision/pipeline/Model.py
> +    def predict(self, image: np.ndarray):
Recatored to handle an array of images.

2021-02-14 23:08 UTC, dpalencia commented
Documenting this for later--I believe the testing suite assertion is failing on the last commit because of discrepancies in SKLearn versions.

>   /home/travis/miniconda/envs/marsvision/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.23.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.

2021-02-16 05:51 UTC, dpalencia commented on marsvision/pipeline/SlidingWindow.py
> +            for x in range(0, image.shape[1], self.stride_y):
These should be handled by lines 82-83, where the windows are taken to be min(x + window_width, image_width) for the horizontal axis; same thing for the vertical axis. This behavior can be seen in the sliding window notebook, where the windows on the edges are thin slices.

2021-02-16 22:21 UTC, michaelmunje approved these changes

2021-02-17 02:52 UTC, merged